[project]
name = "ee215a-project-7"
version = "0.1.0"
description = "Simple Microarchitecture Design Space Exploration Algorithm"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "iccad-contest==0.0.9",
    "pymoo>=0.6.1.5",
    "torch>=2.7.0",
]
