[project]
name = "ee215a-project-7"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "iccad-contest==0.0.9",
    "torch>=2.7.0",
]
